# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CheckovDocs < Formula
  desc "Generate docs for `checkov` results"
  homepage "https://github.com/checkov-docs/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/checkov-docs/checkov-docs/releases/download/v0.1.0/checkov-docs-v0.1.0-darwin-amd64.tar.gz"
      sha256 "fb38e76268f837ea98f07ebaa7157e67bcfcade6d9d24f2a894fdf81bec5062c"

      def install
        bin.install "checkov-docs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/checkov-docs/checkov-docs/releases/download/v0.1.0/checkov-docs-v0.1.0-darwin-arm64.tar.gz"
      sha256 "abc2ac5e824cea6a9eb670d242276c171ba21e6de778c92e1651776698c4f9b6"

      def install
        bin.install "checkov-docs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/checkov-docs/checkov-docs/releases/download/v0.1.0/checkov-docs-v0.1.0-linux-arm64.tar.gz"
      sha256 "79c3a5c2f079a312fc13e7ca76e293b26ad66e43699a35975f001b510c951583"

      def install
        bin.install "checkov-docs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/checkov-docs/checkov-docs/releases/download/v0.1.0/checkov-docs-v0.1.0-linux-amd64.tar.gz"
      sha256 "9402877710af4357ae54e24b3fa082b8ec767e1002345b1cbd9021faf4d3f620"

      def install
        bin.install "checkov-docs"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/checkov-docs/checkov-docs/releases/download/v0.1.0/checkov-docs-v0.1.0-linux-arm.tar.gz"
      sha256 "a2a196c3f80090ddd99156704fc18006b2335eaea02a9d0f7c107ca3f13ed274"

      def install
        bin.install "checkov-docs"
      end
    end
  end

  test do
    system "#{bin}/checkov-docs version"
  end
end
